repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
        exclude: ^submodules/
      - id: end-of-file-fixer
        exclude: ^submodules/
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: ^submodules/
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: ^submodules/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        args:
          - "--python-version=3.13"
          - "--ignore-missing-imports"
        exclude: ^submodules/
