repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
        exclude: ^submodules/|sample/logs/
      - id: end-of-file-fixer
        exclude: ^submodules/|sample/logs/
      - id: mixed-line-ending
        args: ["--fix=crlf"]
        exclude: ^submodules/|sample/logs/
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: ^submodules/|sample/logs/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        args:
          - "--python-version=3.13"
          - "--ignore-missing-imports"
        additional_dependencies:
          - types-requests>=2.32.4.20250913
        exclude: ^submodules/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.39.1
    hooks:
      - id: eslint
        files: \.(ts|tsx|js|jsx)$
        args: ["--fix"]
        exclude: ^submodules/|sample/logs/
